# Generated by Django 5.1.7 on 2025-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'price')},
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
