# Generated by Django 5.1.7 on 2025-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
